export default {
    NETWORK_ERROR: 'NETWORK_ERROR',
    NETWORK_TIMEOUT: 'NETWORK_TIMEOUT',
    REQUEST_ABORTED: 'REQUEST_ABORTED',
    LOAD_ERROR: 'LOAD_ERROR',
    CLIENT_ERROR: 'CLIENT_ERROR',
}